name: tagr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  meta:
  file_picker: ^8.0.6
  filesystem_picker: ^4.1.0
  mime:
  protobuf: 
  path:
  flutter_resizable_container: ^2.0.0
  logger: ^2.4.0
  grouped_list: ^6.0.0
  dart_casing: 
  collection:
  permission_handler: ^11.3.1
  dropdown_search: ^5.0.6
  dismissible_page: ^1.0.2
  transparent_image: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  protoc_builder: 
  build_runner:

flutter:
  uses-material-design: true
  assets:
   - assets/images/
