on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Build & Release
jobs: 
  build-and-release-windows:
    name: Build & Release for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '3.22.2'
      - name: Install Dependencies
        run: flutter pub get
      - name: Build intermediates
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build Windows
        run: flutter build windows --release
      - name: Create Build Archive
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: tagr-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name: Release Windows
        uses: softprops/action-gh-release@v1
        with:
          artifacts: "build/windows/runner/Release/tagr-${{github.ref_name}}-windows.zip"
          tag: ${{github.ref_name}}-build-${{github.run_number}}
          token: ${{ secrets.TOKEN }}
